# To install, run:
# pre-commit clean
# pre-commit install sets it up so this runs before every commit happens
# pre-commit install-hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: pretty-format-json
        args: ["--indent", "2", "--no-sort-keys", "--autofix"]

  # Run the linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: Run MyPy
        entry: uv run mypy .
        language: system
        always_run: true
        pass_filenames: false

      - id: deptry
        name: Run Deptry
        entry: uv run deptry .
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: Run PyTest
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
        always_run: true
