# To install, run:
# pre-commit clean
# pre-commit install sets it up so this runs before every commit happens
# pre-commit install-hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: ["--fix=lf"]
    -   id: pretty-format-json
        args: ["--indent", "2", "--no-sort-keys", "--autofix"]

  # Keep the lock file up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.13
    hooks:
      - id: uv-lock

  # Run the linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

  # Run the ty type checker, mypy, deptry, and pytest
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check .
        language: system
      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
      - id: deptry
        name: deptry
        entry: uv run deptry .
        language: system
      - id: pytest
        name: pytest
        entry: uv run pytest .
        language: system
        always_run: true